# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iOSFCMApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase Pods
  pod 'Firebase/Core', '~> 10.0'
  pod 'Firebase/Messaging', '~> 10.0'

  # Optional: Firebase Analytics
  # pod 'Firebase/Analytics'

  target 'iOSFCMAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSFCMAppUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
